version: 2

project_name: scai

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: scai
    binary: scai
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}
      - -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: scai
    builds:
      - scai
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - CLAUDE.md
      - configs/**/*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .ShortCommit }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^refactor:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
  name_template: "{{ .ProjectName }} {{ .Version }}"
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## {{ .ProjectName }} {{ .Version }}

    **Release Date**: {{ .Date }}
    **Git Commit**: `{{ .ShortCommit }}`

    ### 🚀 Installation

    #### Download Binary
    Download the appropriate binary for your platform from the assets below.

    #### Using Go Install
    ```bash
    go install github.com/Smana/scai@{{ .Tag }}
    ```

    #### Verify Checksums
    ```bash
    sha256sum -c checksums.txt
    ```

  footer: |
    ### 📚 Documentation

    - [Project Instructions](https://github.com/{{ .Env.GITHUB_REPOSITORY }}/blob/{{ .Tag }}/CLAUDE.md)

    ---

    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}
