version: 2

project_name: scia

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: scia
    binary: scia
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}
      - -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: scia
    builds:
      - scia
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - CLAUDE.md
      - configs/**/*

dockers:
  - id: scia-amd64
    image_templates:
      - "ghcr.io/smana/scia:{{ .Version }}-amd64"
      - "ghcr.io/smana/scia:latest-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Smart Cloud Infrastructure Automation - AI-powered deployment strategy tool
      - --label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_REPOSITORY }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

  - id: scia-arm64
    image_templates:
      - "ghcr.io/smana/scia:{{ .Version }}-arm64"
      - "ghcr.io/smana/scia:latest-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Smart Cloud Infrastructure Automation - AI-powered deployment strategy tool
      - --label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_REPOSITORY }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  - name_template: "ghcr.io/smana/scia:{{ .Version }}"
    image_templates:
      - "ghcr.io/smana/scia:{{ .Version }}-amd64"
      - "ghcr.io/smana/scia:{{ .Version }}-arm64"
  - name_template: "ghcr.io/smana/scia:latest"
    image_templates:
      - "ghcr.io/smana/scia:latest-amd64"
      - "ghcr.io/smana/scia:latest-arm64"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .ShortCommit }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^refactor:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
  name_template: "{{ .ProjectName }} {{ .Version }}"
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## {{ .ProjectName }} {{ .Version }}

    **Release Date**: {{ .Date }}
    **Git Commit**: `{{ .ShortCommit }}`

    ### 🚀 Installation

    #### Download Binary
    Download the appropriate binary for your platform from the assets below.

    #### Using Go Install
    ```bash
    go install github.com/Smana/scia@{{ .Tag }}
    ```

    #### Container Images
    ```bash
    # Pull the latest release
    docker pull ghcr.io/smana/scia:{{ .Version }}

    # Run a deployment
    docker run ghcr.io/smana/scia:{{ .Version }} deploy "Deploy Flask app" https://github.com/example/repo
    ```

    #### Verify Checksums
    ```bash
    sha256sum -c checksums.txt
    ```

  footer: |
    ### 📚 Documentation

    - [Project Instructions](https://github.com/{{ .Env.GITHUB_REPOSITORY }}/blob/{{ .Tag }}/CLAUDE.md)
    - [Implementation Status](https://github.com/{{ .Env.GITHUB_REPOSITORY }}/blob/{{ .Tag }}/IMPLEMENTATION_STATUS.md)

    ---

    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}
